# Generated by Django 5.2.3 on 2025-07-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='cover_pics/default.jpg', upload_to='cover_pics/'),
        ),
    ]
