# Generated by Django 5.2.3 on 2025-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_read_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('friend_request', 'Friend Request'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
